// ============================================
// Mock Data — Development-time fake data
// Ready to replace with real API calls
// ============================================

export const mockUsers = {
  citizen: {
    id: 'u-001',
    name: 'Arjun Mehta',
    email: 'arjun@example.com',
    role: 'CITIZEN',
    token: 'mock-jwt-citizen-token',
  },
  authority: {
    id: 'u-002',
    name: 'Priya Sharma',
    email: 'priya@authority.gov',
    role: 'AUTHORITY',
    token: 'mock-jwt-authority-token',
  },
  admin: {
    id: 'u-003',
    name: 'Vikram Singh',
    email: 'vikram@admin.gov',
    role: 'ADMIN',
    token: 'mock-jwt-admin-token',
  },
};

export const mockIssues = [
  {
    id: 'issue-001',
    title: 'Water leakage on MG Road — pipe burst under sidewalk',
    description: 'A major water pipe has burst underneath the sidewalk near MG Road Metro Station. Clean water is being wasted and the sidewalk is flooded, causing inconvenience to pedestrians. This has been ongoing for 3 days now.',
    category: 'WATER',
    priority: 'HIGH',
    status: 'OPEN',
    latitude: 12.9716,
    longitude: 77.5946,
    address: '42 MG Road, Near Metro Station',
    ward: 'Ward 5',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560001',
    upvotes: 47,
    commentCount: 12,
    anonymous: false,
    reportedBy: { name: 'Arjun Mehta', id: 'u-001' },
    createdAt: '2026-06-10T08:30:00Z',
    updatedAt: '2026-06-11T14:20:00Z',
    mediaUrls: [],
    comments: [
      { id: 'c-001', author: 'Sunita R.', text: 'This is terrible! I walk past here every day and the water splashes on my shoes.', createdAt: '2026-06-10T10:15:00Z' },
      { id: 'c-002', author: 'BBMP Water Dept.', text: 'We have acknowledged this issue and a repair crew has been dispatched.', createdAt: '2026-06-11T09:00:00Z', isOfficial: true },
      { id: 'c-003', author: 'Raj K.', text: 'Thank you for reporting! The water is mixing with sewage now, please prioritize.', createdAt: '2026-06-11T11:30:00Z' },
    ],
  },
  {
    id: 'issue-002',
    title: 'Massive pothole on Hosur Road causing accidents',
    description: 'A pothole approximately 2 feet wide and 1 foot deep has formed on Hosur Road near the Silk Board junction. Two-wheelers are especially at risk. There have been at least 3 minor accidents in the past week.',
    category: 'ROAD',
    priority: 'CRITICAL',
    status: 'ASSIGNED',
    latitude: 12.9177,
    longitude: 77.6238,
    address: 'Hosur Road, Near Silk Board',
    ward: 'Ward 12',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560068',
    upvotes: 128,
    commentCount: 24,
    anonymous: false,
    reportedBy: { name: 'Neha Gupta', id: 'u-004' },
    createdAt: '2026-06-08T06:45:00Z',
    updatedAt: '2026-06-12T08:00:00Z',
    mediaUrls: [],
    comments: [
      { id: 'c-010', author: 'Traffic Police', text: 'We have placed temporary barricades. Road repair team has been notified.', createdAt: '2026-06-09T07:00:00Z', isOfficial: true },
    ],
  },
  {
    id: 'issue-003',
    title: 'Street lights non-functional on 5th Cross, Jayanagar',
    description: 'All street lights on 5th Cross Road in Jayanagar 4th Block have been non-functional for over a week. The entire stretch is pitch dark after 6 PM, making it unsafe for residents.',
    category: 'STREET_LIGHT',
    priority: 'MEDIUM',
    status: 'IN_PROGRESS',
    latitude: 12.9266,
    longitude: 77.5816,
    address: '5th Cross, 4th Block Jayanagar',
    ward: 'Ward 38',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560041',
    upvotes: 32,
    commentCount: 5,
    anonymous: false,
    reportedBy: { name: 'Kavitha S.', id: 'u-005' },
    createdAt: '2026-06-05T18:20:00Z',
    updatedAt: '2026-06-11T16:45:00Z',
    mediaUrls: [],
    comments: [],
  },
  {
    id: 'issue-004',
    title: 'Garbage piling up at Koramangala Market',
    description: 'The waste bins at Koramangala 4th Block market area have not been cleared for 5 days. The stench is unbearable and attracting stray animals. Residents and shop owners are severely affected.',
    category: 'SANITATION',
    priority: 'HIGH',
    status: 'OPEN',
    latitude: 12.9352,
    longitude: 77.6245,
    address: 'Koramangala 4th Block Market',
    ward: 'Ward 15',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560034',
    upvotes: 89,
    commentCount: 18,
    anonymous: false,
    reportedBy: { name: 'Rahul M.', id: 'u-006' },
    createdAt: '2026-06-09T07:00:00Z',
    updatedAt: '2026-06-11T10:30:00Z',
    mediaUrls: [],
    comments: [],
  },
  {
    id: 'issue-005',
    title: 'Sewage overflow in residential area — HSR Layout',
    description: 'Sewage is overflowing from a manhole on Sector 2, HSR Layout. The contaminated water is spreading to the road and nearby houses. Multiple residents have reported health concerns.',
    category: 'SEWAGE',
    priority: 'CRITICAL',
    status: 'RESOLVED',
    latitude: 12.9081,
    longitude: 77.6476,
    address: 'Sector 2, HSR Layout',
    ward: 'Ward 22',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560102',
    upvotes: 67,
    commentCount: 15,
    anonymous: false,
    reportedBy: { name: 'Anjali R.', id: 'u-007' },
    createdAt: '2026-06-03T09:00:00Z',
    updatedAt: '2026-06-10T14:00:00Z',
    mediaUrls: [],
    comments: [],
  },
  {
    id: 'issue-006',
    title: 'Illegal construction blocking public park access',
    description: 'An unauthorized structure is being built at the entrance of Cubbon Park Area 3, completely blocking pedestrian access. Construction materials are dumped on the footpath.',
    category: 'ILLEGAL_CONSTRUCTION',
    priority: 'MEDIUM',
    status: 'OPEN',
    latitude: 12.9763,
    longitude: 77.5929,
    address: 'Near Cubbon Park, Area 3',
    ward: 'Ward 8',
    city: 'Bangalore',
    state: 'Karnataka',
    pinCode: '560001',
    upvotes: 23,
    commentCount: 7,
    anonymous: true,
    reportedBy: { name: 'Anonymous', id: 'u-anon' },
    createdAt: '2026-06-11T10:00:00Z',
    updatedAt: '2026-06-11T10:00:00Z',
    mediaUrls: [],
    comments: [],
  },
];

export const mockPolls = [
  {
    id: 'poll-001',
    question: 'Should Bangalore implement congestion pricing for the CBD area?',
    description: 'The city is considering charging vehicles entering the Central Business District during peak hours (8 AM - 10 AM & 5 PM - 8 PM) to reduce traffic congestion.',
    status: 'ACTIVE',
    options: [
      { id: 'opt-001', text: 'Yes, implement immediately', votes: 1240, percentage: 41.3 },
      { id: 'opt-002', text: 'Yes, but with exemptions for residents', votes: 980, percentage: 32.7 },
      { id: 'opt-003', text: 'No, improve public transport first', votes: 580, percentage: 19.3 },
      { id: 'opt-004', text: 'No, it will hurt businesses', votes: 200, percentage: 6.7 },
    ],
    totalVotes: 3000,
    votedOptionId: null,
    createdAt: '2026-06-01T00:00:00Z',
    expiresAt: '2026-06-30T23:59:59Z',
    createdBy: 'Transport Department',
  },
  {
    id: 'poll-002',
    question: 'Which area should receive priority road repair funding this quarter?',
    description: 'The BBMP has allocated ₹50 Crore for road repairs. Help us decide which zone should be prioritized.',
    status: 'ACTIVE',
    options: [
      { id: 'opt-005', text: 'Outer Ring Road (ORR)', votes: 850, percentage: 34.0 },
      { id: 'opt-006', text: 'Whitefield - ITPL Road', votes: 720, percentage: 28.8 },
      { id: 'opt-007', text: 'Bannerghatta Road', votes: 530, percentage: 21.2 },
      { id: 'opt-008', text: 'Old Airport Road', votes: 400, percentage: 16.0 },
    ],
    totalVotes: 2500,
    votedOptionId: 'opt-006',
    createdAt: '2026-06-05T00:00:00Z',
    expiresAt: '2026-06-25T23:59:59Z',
    createdBy: 'BBMP Roads Division',
  },
  {
    id: 'poll-003',
    question: 'Do you support the proposed metro extension to Electronic City?',
    description: 'BMRCL is planning to extend the Purple Line to Electronic City via Silk Board. This will require partial road closures for 18 months.',
    status: 'CLOSED',
    options: [
      { id: 'opt-009', text: 'Strongly support', votes: 4200, percentage: 52.5 },
      { id: 'opt-010', text: 'Support with conditions', votes: 2400, percentage: 30.0 },
      { id: 'opt-011', text: 'Oppose — too disruptive', votes: 800, percentage: 10.0 },
      { id: 'opt-012', text: 'Need more information', votes: 600, percentage: 7.5 },
    ],
    totalVotes: 8000,
    votedOptionId: 'opt-009',
    createdAt: '2026-05-01T00:00:00Z',
    expiresAt: '2026-05-31T23:59:59Z',
    createdBy: 'BMRCL',
  },
];

export const mockAnalytics = {
  dashboard: {
    totalIssues: 2847,
    resolvedIssues: 1923,
    openIssues: 924,
    totalVotes: 13500,
    avgResolutionDays: 4.2,
    citizenSatisfaction: 78,
  },
  sla: [
    { department: 'Water Supply', complianceRate: 92, totalIssues: 420, withinSla: 386 },
    { department: 'Roads', complianceRate: 68, totalIssues: 680, withinSla: 462 },
    { department: 'Sanitation', complianceRate: 85, totalIssues: 510, withinSla: 434 },
    { department: 'Street Lights', complianceRate: 95, totalIssues: 290, withinSla: 276 },
    { department: 'Sewage', complianceRate: 73, totalIssues: 350, withinSla: 256 },
    { department: 'Parks', complianceRate: 88, totalIssues: 180, withinSla: 158 },
  ],
  trends: {
    labels: ['Jun 1', 'Jun 2', 'Jun 3', 'Jun 4', 'Jun 5', 'Jun 6', 'Jun 7', 'Jun 8', 'Jun 9', 'Jun 10', 'Jun 11', 'Jun 12'],
    submitted: [45, 52, 38, 61, 55, 48, 32, 58, 67, 42, 71, 63],
    resolved: [30, 35, 42, 28, 45, 38, 25, 40, 50, 35, 48, 55],
  },
  categories: [
    { name: 'Roads', count: 680, color: '#f97316' },
    { name: 'Water Supply', count: 420, color: '#3b82f6' },
    { name: 'Sanitation', count: 510, color: '#10b981' },
    { name: 'Street Lights', count: 290, color: '#f59e0b' },
    { name: 'Sewage', count: 350, color: '#8b5cf6' },
    { name: 'Parks', count: 180, color: '#14b8a6' },
    { name: 'Noise', count: 120, color: '#ec4899' },
    { name: 'Electricity', count: 197, color: '#eab308' },
    { name: 'Other', count: 100, color: '#6b7280' },
  ],
};

export const mockNotifications = [
  { id: 'n-001', type: 'status_change', title: 'Issue status updated', description: 'Your issue "Water leakage on MG Road" has been changed from <strong>OPEN</strong> to <strong>ASSIGNED</strong>.', time: '5 min ago', read: false },
  { id: 'n-002', type: 'comment', title: 'New official response', description: 'BBMP Water Dept. commented on your issue "Water leakage on MG Road".', time: '1 hour ago', read: false },
  { id: 'n-003', type: 'status_change', title: 'Issue resolved', description: 'Your issue "Sewage overflow in HSR Layout" has been marked as <strong>RESOLVED</strong>.', time: '3 hours ago', read: true },
  { id: 'n-004', type: 'assignment', title: 'New assignment', description: 'A new WATER category issue has been assigned to your department.', time: '5 hours ago', read: true },
  { id: 'n-005', type: 'sla_breach', title: 'SLA Deadline Warning', description: '⚠️ Issue "Pothole on Hosur Road" is approaching its SLA deadline.', time: '6 hours ago', read: true },
  { id: 'n-006', type: 'status_change', title: 'Issue in progress', description: 'Your issue "Street lights on 5th Cross" is now <strong>IN PROGRESS</strong>.', time: '1 day ago', read: true },
];

export const mockAuditLogs = [
  { id: 'a-001', timestamp: '2026-06-12T10:30:00Z', action: 'STATUS_CHANGED', entityType: 'Issue', entityId: 'issue-001', actor: 'priya@authority.gov', oldValue: { status: 'OPEN' }, newValue: { status: 'ASSIGNED', assignedTo: 'Water Supply Dept.' } },
  { id: 'a-002', timestamp: '2026-06-12T09:15:00Z', action: 'CREATED', entityType: 'Poll', entityId: 'poll-001', actor: 'vikram@admin.gov', oldValue: null, newValue: { question: 'Should Bangalore implement congestion pricing?', options: 4 } },
  { id: 'a-003', timestamp: '2026-06-11T16:45:00Z', action: 'STATUS_CHANGED', entityType: 'Issue', entityId: 'issue-003', actor: 'priya@authority.gov', oldValue: { status: 'ASSIGNED' }, newValue: { status: 'IN_PROGRESS', note: 'Repair crew dispatched' } },
  { id: 'a-004', timestamp: '2026-06-11T14:20:00Z', action: 'COMMENT_ADDED', entityType: 'Issue', entityId: 'issue-001', actor: 'water-dept@bbmp.gov', oldValue: null, newValue: { comment: 'We have acknowledged this issue and a repair crew has been dispatched.' } },
  { id: 'a-005', timestamp: '2026-06-10T14:00:00Z', action: 'STATUS_CHANGED', entityType: 'Issue', entityId: 'issue-005', actor: 'priya@authority.gov', oldValue: { status: 'IN_PROGRESS' }, newValue: { status: 'RESOLVED', resolutionNote: 'Manhole repaired and area cleaned.' } },
  { id: 'a-006', timestamp: '2026-06-10T08:30:00Z', action: 'CREATED', entityType: 'Issue', entityId: 'issue-001', actor: 'arjun@example.com', oldValue: null, newValue: { title: 'Water leakage on MG Road', category: 'WATER', priority: 'HIGH' } },
  { id: 'a-007', timestamp: '2026-06-09T12:00:00Z', action: 'ROLE_CHANGED', entityType: 'User', entityId: 'u-002', actor: 'vikram@admin.gov', oldValue: { role: 'CITIZEN' }, newValue: { role: 'AUTHORITY' } },
  { id: 'a-008', timestamp: '2026-06-08T06:45:00Z', action: 'CREATED', entityType: 'Issue', entityId: 'issue-002', actor: 'neha@example.com', oldValue: null, newValue: { title: 'Massive pothole on Hosur Road', category: 'ROAD', priority: 'CRITICAL' } },
];

export const mockUsersList = [
  { id: 'u-001', name: 'Arjun Mehta', email: 'arjun@example.com', role: 'CITIZEN', active: true, issuesReported: 12, joinedAt: '2026-01-15' },
  { id: 'u-002', name: 'Priya Sharma', email: 'priya@authority.gov', role: 'AUTHORITY', active: true, issuesReported: 0, joinedAt: '2026-02-01' },
  { id: 'u-003', name: 'Vikram Singh', email: 'vikram@admin.gov', role: 'ADMIN', active: true, issuesReported: 0, joinedAt: '2025-11-10' },
  { id: 'u-004', name: 'Neha Gupta', email: 'neha@example.com', role: 'CITIZEN', active: true, issuesReported: 8, joinedAt: '2026-03-20' },
  { id: 'u-005', name: 'Kavitha S.', email: 'kavitha@example.com', role: 'CITIZEN', active: true, issuesReported: 5, joinedAt: '2026-04-10' },
  { id: 'u-006', name: 'Rahul M.', email: 'rahul@example.com', role: 'CITIZEN', active: false, issuesReported: 3, joinedAt: '2026-05-01' },
  { id: 'u-007', name: 'Anjali R.', email: 'anjali@example.com', role: 'CITIZEN', active: true, issuesReported: 6, joinedAt: '2026-01-25' },
  { id: 'u-008', name: 'Dept. Head — Roads', email: 'roads@authority.gov', role: 'AUTHORITY', active: true, issuesReported: 0, joinedAt: '2026-01-01' },
];
